import { Playfair_Display, Outfit, Poppins } from "next/font/google";
import "./globals.css";
import ThriftContextProvider, { ThriftContext } from '@/Context/ThriftContext'
import { ClerkProvider } from "@clerk/nextjs";

const outfit = Outfit({
  variable: "--font-outfit",
  subsets: ["latin"],
});

const playfair_display = Playfair_Display({
  variable: "--font-playfair-display",
  subsets: ["latin"],
});

const poppins = Poppins({
  variable: "--font-poppins",
  weight: "400",
  subsets: ["latin"],
});

export const metadata = {
  title: "Pastel thrifts",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (

        <ClerkProvider>
    <html lang="en" className="scroll-smooth">
      <body
        className={`${playfair_display.variable} ${poppins.variable} ${outfit.variable} antialiased`}
      >
        <ThriftContextProvider>
        {children}
        </ThriftContextProvider>
      </body>
    </html>
    </ClerkProvider>
  );
}
