import { Playfair_Display, Outfit } from "next/font/google";
import "./globals.css";
import ThriftContextProvider, { ThriftContext } from '@/Context/ThriftContext'
import { ClerkProvider } from "@clerk/nextjs";

const outfit = Outfit({
  variable: "--font-outfit",
  subsets: ["latin"],
});

const playfair_display = Playfair_Display({
  variable: "--font-playfair-display",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (

        <ClerkProvider>
    <html lang="en">
      <body
        className={`${playfair_display.variable} ${outfit.variable} antialiased`}
      >
        <ThriftContextProvider>
        {children}
        </ThriftContextProvider>
      </body>
    </html>
    </ClerkProvider>
  );
}
